name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0, v2.3.1, etc.

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.13'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Extract version
      id: vars
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build EXE with PyInstaller
      run: >
        pyinstaller --onefile --windowed
        --icon=images/favicon.ico
        --name "Bank_ATM_${{ env.VERSION }}"
        --add-data "images/favicon.ico;."
        main.py

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: bank-atm-${{ env.VERSION }}
        path: dist/Bank_ATM_${{ env.VERSION }}.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        files: dist/Bank_ATM_${{ env.VERSION }}.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
