name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0, v2.3.1, etc.

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.13'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: >
        pyinstaller --onefile --windowed
        --icon=images/favicon.ico
        --name "Bank ATM"
        --add-data "images/favicon.ico;."
        main.py
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: bank-atm-exe
        path: dist/Bank ATM.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: dist/Bank ATM.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
